/**
 * 本地图标映射（由 download-icons.js 自动生成，也可手动维护）
 * key: 域名  value: icons/ 目录下的文件名
 */
const ICON_MANIFEST = {
    "cet.neea.edu.cn": "cet.neea.edu.cn.ico",
    "chat.deepseek.com": "chat.deepseek.com.png",
    "chatglm.cn": "chatglm.cn.ico",
    "cli.im": "cli.im.ico",
    "fanyi.baidu.com": "fanyi.baidu.com.ico",
    "gitee.com": "gitee.com.ico",
    "jwc.aust.edu.cn": "jwc.aust.edu.cn.png",
    "kimi.moonshot.cn": "kimi.moonshot.cn.ico",
    "leetcode.cn": "leetcode.cn.ico",
    "lib.aust.edu.cn": "lib.aust.edu.cn.png",
    "matrix.tencent.com": "matrix.tencent.com.ico",
    "metaso.cn": "metaso.cn.ico",
    "mubu.com": "mubu.com.ico",
    "muchong.com": "muchong.com.ico",
    "note.youdao.com": "note.youdao.com.ico",
    "pintia.cn": "pintia.cn.ico",
    "typewords.cc": "typewords.cc.ico",
    "v.qq.com": "v.qq.com.ico",
    "vscode.dev": "vscode.dev.ico",
    "www.51job.com": "www.51job.com.ico",
    "www.aust.edu.cn": "www.aust.edu.cn.png",
    "www.bilibili.com": "www.bilibili.com.ico",
    "www.bing.com": "www.bing.com.ico",
    "www.cctv.com": "www.cctv.com.ico",
    "www.cnki.net": "www.cnki.net.ico",
    "www.coze.cn": "www.coze.cn.png",
    "www.cqvip.com": "www.cqvip.com.ico",
    "www.csdn.net": "www.csdn.net.ico",
    "www.doubao.com": "www.doubao.com.png",
    "www.duoduo.link": "www.duoduo.link.ico",
    "www.icourse163.org": "www.icourse163.org.png",
    "www.ilovepdf.com": "www.ilovepdf.com.ico",
    "www.iqiyi.com": "www.iqiyi.com.ico",
    "www.ixueshu.com": "www.ixueshu.com.ico",
    "www.nowcoder.com": "www.nowcoder.com.ico",
    "www.qianwen.com": "www.qianwen.com.png",
    "www.shixiseng.com": "www.shixiseng.com.ico",
    "www.wanfangdata.com.cn": "www.wanfangdata.com.cn.ico",
    "www.webofscience.com": "www.webofscience.com.ico",
    "www.yingjiesheng.com": "www.yingjiesheng.com.ico",
    "www.youku.com": "www.youku.com.ico",
    "www.zhaopin.com": "www.zhaopin.com.ico",
    "www.zhihuishu.com": "www.zhihuishu.com.ico",
    "www.zhipin.com": "www.zhipin.com.ico",
    "xueshu.baidu.com": "xueshu.baidu.com.ico",
    "yiyan.baidu.com": "yiyan.baidu.com.png",
    "yz.chsi.com.cn": "yz.chsi.com.cn.ico"
};
